# Tell Railway's build system (Nixpacks) to use the "apt" package manager
providers = ["apt"]

# Specify the system-level packages to install during the setup phase
[phases.setup]
aptPkgs = ["ffmpeg"]